PKG_NAME = libopus
PKG_VERS = 1.1
PKG_EXT = tar.gz
PKG_DIST_NAME = opus-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://downloads.xiph.org/releases/opus
PKG_DIR = opus-$(PKG_VERS)

DEPENDS =

HOMEPAGE =
COMMENT  =
LICENSE  =

GNU_CONFIGURE = 1

CONFIGURE_ARGS = --disable-doc --disable-extra-programs

include ../../mk/spksrc.cross-cc.mk

